# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'


target 'Clique' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore',:modular_headers => true

  # Pods for Clique

  target 'CliqueTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Clique-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Clique-tvOS

  target 'Clique-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
